# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: First Terminal
    before: echo Before
    init: echo 'Init script'
    command: echo ' start script - runs on each command'
  - name: Second Terminal
    before echo 'Before Second'
    init: echo 'Second init'
    command: echo ' start in second'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
